def includeme(config):
	# Define routes (first argument should match route_name in views, second argument is the url)
	config.add_static_view('static', 'static', cache_max_age=3600)
	config.add_static_view('css', 'static/css')
	config.add_static_view('images', 'static/images')
	config.add_static_view('js', 'static/js')
	config.add_static_view('datafiles', 'datafiles')

	config.add_route('/session/selecteddataset', '/session/selecteddataset')
	config.add_route('/session/selectedGene', '/session/selectedGene')

	config.add_route('/home', '/')
	config.add_route('/about', '/about')
	config.add_route('/searches', '/searches')
	config.add_route('/search/keyword', '/search/keyword')
	config.add_route('/search/expression', '/search/expression')
	config.add_route('/search/highexp', '/search/highexp')
	config.add_route('/downloadfile', '/downloadfile')

	config.add_route('/login', '/login')
	config.add_route('/logout', '/logout')
	config.add_route('/user/checkusername', '/user/checkusername')
	config.add_route('/user/emailconfirm', '/user/emailconfirm')
	config.add_route('/user/register', '/user/register')
	config.add_route('/user/account', '/user/account')
	config.add_route('/user/update', '/user/update')
	config.add_route('/user/retrieve', '/user/retrieve')
	config.add_route('/user/reset', '/user/reset')
	config.add_route('/user/passreset', '/user/passreset')
	config.add_route('/user/users', '/user/users')
	config.add_route('/user/manage', '/user/manage')
	config.add_route('/user/sendemail', '/user/sendemail')
	config.add_route('/user/usage', '/user/usage')

	config.add_route('/geneset/current', '/geneset/current')
	config.add_route('/geneset/save', '/geneset/save')
	config.add_route('/geneset/rename', '/geneset/rename')
	config.add_route('/geneset/delete', '/geneset/delete')
	config.add_route('/geneset/modify', '/geneset/modify')
	config.add_route('/geneset/orthologue', '/geneset/orthologue')
	config.add_route('/geneset/corr', '/geneset/corr')
	config.add_route('/geneset/heatmap', '/geneset/heatmap')

	config.add_route('/expression/show', '/expression/show')
	config.add_route('/expression/multispecies', '/expression/multispecies')
	config.add_route('/expression/genevsgene', '/expression/genevsgene')

	config.add_route('/datasets/show', '/datasets/show')
	config.add_route('/datasets/analyse', '/datasets/analyse')
	config.add_route('/datasets/samples', '/datasets/samples')
	config.add_route('/datasets/createsubset', '/datasets/createsubset')
	config.add_route('/datasets/select', '/datasets/select')
	config.add_route('/datasets/order', '/datasets/order')

	config.add_route('/grouppages/HiltonLab/samples', '/grouppages/HiltonLab/samples')
	config.add_route('/grouppages/HiltonLab/samples_save', '/grouppages/HiltonLab/samples_save')
	config.add_route('/grouppages/HiltonLab/new_samples_save', '/grouppages/HiltonLab/new_samples_save')
	config.add_route('/grouppages/HiltonLab/delete_samples', '/grouppages/HiltonLab/delete_samples')
	config.add_route('/grouppages/CSL/scoregenes', '/grouppages/CSL/scoregenes')
	config.add_route('/grouppages/CSL/scoregenes_save', '/grouppages/CSL/scoregenes_save')
